#!/usr/bin/env python3
import sys

arquivo = sys.argv[1]

with open(arquivo, 'r') as f:
	results = [[int(entry) for entry in line.split()] for line in f.readlines()]
	print(results)

value = 0
va = 1

for lists in results:
	x = results[value][0]
	y = results[value][1]
	value += 1
	i = x/y
	severity = -0.00942 + 0.0167 + i
	sev = severity * 100
	s = round(sev, 2)
	print(f'Para a planta {va} a incidência da doença é {i} e a severidade é {s}')
	va += 1
	

 
