#!/usr/bin/env python3
import sys
import math

d = sys.argv[1]
a1 = sys.argv[2]
a2 = sys.argv[3]
a3 = sys.argv[4]
a4 = sys.argv[5]
a5 = sys.argv[6]
x = int(a1)
y = int(a2)
z = int(a3)
w = int(a4)
n = int(a5)

if d == 'Banana':
#	a1 = sys.argv[2]
#	a2 = sys.argv[3]
#	a3 = sys.argv[4]
#	a4 = sys.argv[5]
#	a5 = sys.argv[6]
#	x = int(a1)
#	y = int(a2)
#	z = int(a3)
#	w = int(a4)
#	n = int(a5)
	severity = ((0.05*x) + (0.15*y) + (0.35*z) + (0.5*w))/n
	sev = severity*100
	print('Confirmação: A cultura digitada foi {}, equivalente a doença mancha foliar da bananeira. {} equivale ao número de folhas doentes de escala 1. {} equivale ao número de folhas doentes de escala 2. {} equivale ao número de folhas doentes de escala 3. {} equivale ao número de folhas doentes de escala 4. {} equivale ao número total de folhas sintomáticas.'.format(d, a1, a2, a3, a4, a5))
	print('A severidade estimada da doença é {}'.format(round(sev, 2)))
elif d == 'Milho':
	incidence = (x/y)
	severity = (-0.00942 + 0.0167 + incidence)
	sev = severity*100
	print('Confirmação: A cultura digitada foi {}, equivalente a ferrugem comum do milho doce. {} equivale ao número de folhas doentes. {} equivale ao número de folhas total'.format(d, x, y))
	print('A severidade estimada da doença é {}.'.format(round(sev, 2)))
elif d == 'Cacau':
	incidence = (x/y)
	severity = ((1.1625*incidence) + 0.4392)
	sev = severity*100
	print('Confirmação: A cultura digitada foi {}, equivalente a gomose do cacaueiro. {} equivale ao número de folhas doentes. {} equivale ao número de folhas total'.format(d, x, y))
	print('A severidade estimada da doença é {}.'.format(round(sev, 2)))
elif d == 'Café':
	incidence = (x/y)
	severity = 0.001 - (0.01076*incidence) + (0.008376*(incidence**2))
	sev = severity*100
	print('Confirmação: A cultura digitada foi {}, equivalente a ferrugem do café. {} equivale ao número de folhas doentes. {} equivale ao número de folhas total'.format(d, x, y))
	print('A severidade estimada da doença é {}.'.format(round(sev, 5)))
else:
	print('O código de doença inserido foi {}, que não condiz com nenhum dos disponíveis. Os códigos disponíveis são: Banana para mancha foliar da bananeira|Cacau para a gomose do cacaueiro.|Café para a ferrugem do cafeeiro.|Milho para a ferrugem comum do milho doce.'.format(d))

